# Generated by Django 6.0 on 2026-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('footwear', 'Footwear'), ('home-kitchen', 'Home & Kitchen'), ('beauty', 'Beauty'), ('grocery', 'Grocery'), ('books', 'Books'), ('sports', 'Sports'), ('toys-baby', 'Toys & Baby'), ('automotive', 'Automotive'), ('jewellery', 'Jewellery'), ('accessories', 'Accessories')], max_length=50),
        ),
    ]
