# Generated by Django 5.2.10 on 2026-01-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_ord_pro_id_alter_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
