# Generated by Django 5.2.10 on 2026-01-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_user_id_to_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_uuid',
            new_name='user_id',
        ),
    ]
