# Generated by Django 5.2.10 on 2026-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
