# Generated by Django 6.0 on 2026-01-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
