# Generated by Django 5.2.10 on 2026-01-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_users_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
