# Generated by Django 5.2.10 on 2026-01-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user_uuid',
        ),
    ]
