# Generated by Django 6.0 on 2026-01-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_pro_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
