# Generated by Django 5.2.10 on 2026-01-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_products'),
        ('products', '0005_alter_products_id'),
        ('register', '0002_alter_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.users')),
            ],
        ),
    ]
