# Generated by Django 6.0 on 2026-01-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_desc', models.TextField()),
                ('pro_price', models.FloatField()),
                ('pro_category', models.CharField(default='', max_length=50)),
                ('pro_stock', models.IntegerField(default=0)),
                ('pro_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
