# Generated by Django 6.0 on 2026-01-18 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_pro_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pro_id',
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
