# Generated by Django 6.0 on 2026-01-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_pro_id_products_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='pro_id',
        ),
    ]
